package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"strings"

	"github.com/AlexJarrah/queryc/internal/dialect"
	"github.com/AlexJarrah/queryc/internal/model"
)

// Generate returns the Go bindings for the provided schema and queries.
func Generate(schema model.Schema, imports []model.Import, queries []model.AnalyzedQuery, d model.Dialect, pkg string) ([]byte, error) {
	schemasPkg, err := resolveSchemaPackage(schema, imports)
	if err != nil {
		return nil, err
	}

	if err := validateGenerationInputs(schema, queries, d); err != nil {
		return nil, err
	}

	pkg, err = resolvePackageName(d, pkg)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("// Generated by queryc. DO NOT EDIT.\n")

	buf.WriteString("package ")
	buf.WriteString(pkg)
	buf.WriteByte('\n')

	writeImports(&buf, imports, d, schema, queries)
	writeConstants(&buf, schema)
	writeCustomQueries(&buf, queries, schemasPkg)
	writeCRUD(&buf, schema, d, schemasPkg)
	if d == model.DialectPostgres {
		writePrepareStatements(&buf, schema, queries, d)
	}
	writeResultStructs(&buf, queries, schemasPkg)

	if _, err := parser.ParseFile(token.NewFileSet(), "bindings.go", buf.Bytes(), parser.AllErrors); err != nil {
		return nil, fmt.Errorf("generated code is invalid: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated code formatting failed: %w", err)
	}
	return formatted, nil
}

func resolvePackageName(d model.Dialect, pkg string) (string, error) {
	name := strings.TrimSpace(pkg)
	if name == "" {
		return dialect.PackageName(d), nil
	}
	if !token.IsIdentifier(name) {
		return "", fmt.Errorf("invalid package name %q", name)
	}
	return name, nil
}
